server:
  port: 8080
  servlet:
    context-path: /

spring:
  application:
    name: tesora-gateway

  cloud:
    gateway:

      routes:

        # 🟢 AUTHSERVICE usando Eureka ahora
        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/gateway/auth-service/api/authentication/**
          filters:
           - StripPrefix=1 

        - id: grupos-service
          uri: http://localhost:8081/grupos-service
          predicates:
            - Path=/gateway/grupos-service/api/grupos/**
          filters:
            - StripPrefix=1						

eureka:
  client:
    fetch-registry: true
    service-url:
      defaultZone: ${eureka.registry-server}

management:
  endpoints:
    web:
      exposure:
        include: health, info

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
