server:
  port: 8080
  servlet:
    context-path: /

spring:
  application:
    name: gateway-service

  profiles:
    active: oauth2


eureka:
  client:
    fetch-registry: true
    service-url:
      #defaultZone: ${eureka.registry-server}
      defaultZone: http://localhost:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: health, info

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
