###
##
#
server:
  port: 8080
  servlet:
    context-path: /
  netty:
    connection-timeout: 30s

spring:
  application:
    name: gateway-service

  profiles:
    active: oauth2

  cloud:
    gateway:
      httpclient:
        connect-timeout: 3000 # Tiempo máximo para conectar al microservicio (milisegundos)
        response-timeout: 5s   # Tiempo máximo para recibir respuesta
        pool:
          type: elastic        # Usa un pool elástico que crece y se limpia solo
          max-connections: 5000 # Límite total de conexiones HTTP mantenidas
          acquire-timeout: 5000 # Espera máximo 5 segundos para obtener conexión libre

eureka:
  client:
    fetch-registry: true
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE}
      #defaultZone: ${eureka.registry-server}
      #defaultZone: http://192.168.100.23:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: health, info
  endpoint:
    health:
      show-details: always

logging:
  level:
    root: INFO
    org.springframework.cloud.gateway: WARN
    org.springframework.web.reactive.function.client.ExchangeFunctions: ERROR
    com.tesoramobil.gateway: DEBUG


jwt:
  secret: ${JWT_SECRET}


