server:
  port: 8080
  servlet:
    context-path: /

spring:
  application:
    name: gateway-service

  profiles:
   default: dev 	

  config:
    import: ${SPRING_CONFIG_IMPORT} # Importa la configuración externa desde config-server
    #import: optional:configserver:http://localhost:7777/
  
  cloud:
    gateway:

      routes:

        # 🟢 AUTHSERVICE usando Eureka ahora
        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/gateway/auth-service/api/authentication/**
          filters:
           - StripPrefix=1 

        - id: grupos-service
          uri: lb://grupos-service
          predicates:
            - Path=/gateway/grupos-service/api/grupos/**
          filters:
            - StripPrefix=1						

eureka:
  client:
    fetch-registry: true
    service-url:
      defaultZone: ${eureka.registry-server}

management:
  endpoints:
    web:
      exposure:
        include: health, info

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
