server:
  port: 8080                    # Puerto en el que levanta el Gateway
  servlet:
    context-path: /             # Context path raíz ("/") para recibir todas las rutas

spring:
  application:
    name: tesora-gateway        # Nombre lógico de la aplicación (útil en logs y métricas)

  cloud:
    gateway:
      default-filters:          # Filtros que se aplican a todas las rutas definidas
        - RewriteLocationResponseHeader=X-Forwarded-Prefix, .
                                 # Cuando el downstream hace un redirect (Location), reescribe la cabecera
                                 # añadiendo el prefijo original que llegó al Gateway

      routes:                   # Lista de rutas que define hacia dónde enrutar
        - id: auth              # Identificador único de la ruta “auth”
          uri: lb://auth-service 
                                 # URL base del servicio de autenticación (downstream)
          predicates:
            - Path=/gateway/api/authentication/**  
                                 # Patrón de ruta; cuando la petición cumpla, se aplica esta ruta
          filters:
            - StripPrefix=2      # Antes de reenviar, elimina el primer segmento (“/api”) de la URI

